### ISSUE TITLE
Not refreshed Image

### ISSUE THREAD

**Issue by ablyBikramjeet** [SDWebImage/SDWebImageSVGCoder#12]
Hello Team,

Thanks a lot for make a good library for SVG images.

I want to show both .SVG and any-other type of image. I have showed images successfully but the problem is when i update the image from server but am showing previous image. Run time changed images not working. Please suggest me how i can show new images at run time. Thanks.

**Comment by dreampiggy** [comment]
This because SDWebImage’s cache system, by default use an agressive cache control based on Native code’s expiration age and size. It does not follow any HTTP cache control like Cache-Control Etag...

For this case, you can use the `.refreshCached` option, which will use the HTTP cache control, if your server update the remote resource, the exist cache will  be replaced

**Comment by ablyBikramjeet** [comment]
Thanks for your quick response.

I am explaining you please help me :- 

Suppose I have used cell.cuisinesImageView.sd_setImage(with: cellVM.cuisineImageURL). 
and all images comes in without .svg format. In this case everything working fine.

But I want to show .SVG images and put the below code

let SVGCoder = SDImageSVGCoder.shared
SDImageCodersManager.shared.addCoder(SVGCoder)
 cell.cuisinesImageView.sd_setImage(with: cellVM.cuisineImageURL)

In this case nothing happed always previous image shows.

So please tell me how I can resolve this problem.

**Comment by ablyBikramjeet** [comment]
One more thing .svg image not showing as original these are. From backend I got coloured images but when i shows in my code in is showing black and white. How I resolved this issue also.
![Screenshot 2019-11-26 at 6 11 22 PM](https://user-images.githubusercontent.com/52451314/69634602-96c78700-1078-11ea-949a-467505d919f5.png)

![Screenshot 2019-11-26 at 6 11 12 PM](https://user-images.githubusercontent.com/52451314/69634608-9a5b0e00-1078-11ea-8537-c9115d99eaaf.png)

**Comment by dreampiggy** [comment]
> let SVGCoder = SDImageSVGCoder.shared
> SDImageCodersManager.shared.addCoder(SVGCoder)

This code is the setup code, you should always put it on the AppDelegate (or anything after launch), not before View Controller load and execute multiple times.

Then, can you try to load these SVG files in Xcode 11 ? Xcode 11 support the SVG vector format, if this can not showing correctly in Xcode, it can not showing correctly in iOS as well. The iOS 13 system support for SVG is not always 100% compatbile for W3C SVG standard, which is a subset.

See more:
[Creating Custom Symbol Images for Your App](https://developer.apple.com/documentation/xcode/creating_custom_symbol_images_for_your_app?language=objc)

**Comment by dreampiggy** [comment]
> From backend I got coloured images but when i shows in my code in is showing black and white. How I resolved this issue also.

Sorry, I didn't catch with this description at the above comment.

iOS UIImageView can render symbol as vector image (template), which have a Tint Color. Can be used to render the desired color. The SVG is one type of symbol image, so it also follow that design (allows you to override the color)

Which means, if you need to render SVG, you'd better configurate your UIImageView/UIImage to use the original image. Maybe I need to update some code about this framework ?

```objective-c
UIImage *originalImage;
UIImage *image = [originalImage imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
imageView.image = image;

// Or
UIImageView.tintColor = UIColor.clearColor;
```

See more here: [Configuring and Displaying Symbol Images in Your UI](https://developer.apple.com/documentation/uikit/uiimage/configuring_and_displaying_symbol_images_in_your_ui/)

**Comment by dreampiggy** [comment]
Can you upload those SVG have rendering issue here, to let me test it on our demo project ?

**Comment by ablyBikramjeet** [comment]
Hello @dreampiggy ,

Thanks a lot for your response.

Here, am sending you .svg images URL so you can used this in your demo project.

1) http://test.yoyumm.4livedemo.com/image/cuisines/3/400/400
2) http://test.yoyumm.4livedemo.com/image/cuisines/2/400/400

Please let me know. What is your feedback on this.

Waiting for your positive response.

Thanks & Best Regards,

**Comment by dreampiggy** [comment]
Works on Demo:

![image](https://user-images.githubusercontent.com/6919743/69699937-2e35e400-1124-11ea-88b4-27875f7e3410.png)

**Comment by ablyBikramjeet** [comment]
Can you tell me the steps how you can doing this.

**Comment by dreampiggy** [comment]
One silly question : Are you using SVGKit (which this coder v0.1-0.3 based on, now deprecated) ? It moved to another repo, fire issue there [SDWebImageSVGKitPlugin](https://github.com/SDWebImage/SDWebImageSVGKitPlugin).

---

But actually, for any **Render issue** related to SVGKit, we can not help. Because they're not active developed, and no one contribute code there. We have no knowledge to modify that third party library to figure out the SVG implementation issues.

**Comment by dreampiggy** [comment]
> Can you tell me the steps how you can doing this.

Just using the code in the demo project. Like this:

```objective-c
NSURL *svgURL = [NSURL URLWithString:@"http://test.yoyumm.4livedemo.com/image/cuisines/3/400/400"];
UIImageView *imageView1 = [[UIImageView alloc] init];
imageView1.frame = CGRectMake(0, 0, screenSize.width, screenSize.height / 2);
imageView1.contentMode = UIViewContentModeScaleAspectFit;
[imageView1 sd_setImageWithURL:svgURL];
```

**Comment by ablyBikramjeet** [comment]
@dreampiggy Can you tell which pod i need to install. It's good if you can send me demo project.

**Comment by dreampiggy** [comment]
....This GitHub repo itself? I can not get the point. This repo is what we called SVG plugin 😅 

https://github.com/SDWebImage/SDWebImageSVGCoder.git

**Comment by ablyBikramjeet** [comment]
Wait please let me know which pod file i need to install in my project.

 pod 'SDWebImageSVGCoder'
  pod 'SDWebImageSVGKitPlugin'

**Comment by ablyBikramjeet** [comment]
@dreampiggy I have used below step according to your suggestion but not able to show .svg image.

Step 1. I have created project in Objective C.
Step 2. I have installed below mentioned pods :- 
pod 'SDWebImageSVGCoder'
pod 'SDWebImageSVGKitPlugin
Step 2. I have include #import <SDWebImageSVGCoder/SDWebImageSVGCoder.h>
             and this code in App Delegate File.
           SDImageSVGCoder *SVGCoder = [SDImageSVGCoder sharedCoder];
          [[SDImageCodersManager sharedManager] addCoder:SVGCoder];

Step3. According your last message I have done below Code in View Controller.
            NSURL *svgURL = [NSURL 
           URLWithString:@"http://test.yoyumm.4livedemo.com/image/cuisines/3/400/400"];
          UIImageView *imageView1 = [[UIImageView alloc] init];
         imageView1.frame = CGRectMake(100.0, 200.0, 200.0, 200.0);
        imageView1.contentMode = UIViewContentModeScaleAspectFit;
       [imageView1 sd_setImageWithURL:svgURL];
       [imageView1 setBackgroundColor:UIColor.redColor];
      [self.view addSubview:imageView1];
and Got this output -

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-27 at 13 56 00](https://user-images.githubusercontent.com/52451314/69706415-ab118f80-111d-11ea-92e0-b2ef5b1a590d.png)

Please help me...

**Comment by dreampiggy** [comment]
> http

Enable the App Transport Security -> Allow arbitrary load in Info.plist

**Comment by ablyBikramjeet** [comment]
@dreampiggy . Thanks a lot for your response and am able to do this in demo project with Objective-C and Swift also but am unable to do this my actually project can you tell me any solution for this.

**Comment by dreampiggy** [comment]
> @dreampiggy . Thanks a lot for your response and am able to do this in demo project with Objective-C and Swift also but am unable to do this my actually project can you tell me any solution for this.

Emm. Maybe it's about something your real project's ImageView configuration ? Or you test device's system ?

1. This plugin support iOS 13+only (SVGKit support iOS 8+).
2. You should register the coder plugins, using debugger to check whether `SDImageCodersManager.sharedManager.coders` array contains this SVG Coder
3. Check the network issue, does the SVG image data downloaded success ?
4. Set a break point in our code, `-[SDImageSVGCoder decodeImageWithData:options:]`, see result whether this is get called

**Comment by ablyBikramjeet** [comment]
Sure @dreampiggy . Thanks a lot for your support...

**Comment by dreampiggy** [comment]
This plugin is actually backward-deployable. If you need to support both iOS 12/13, you need to use these two plugins at the same time.

+ SDWebImageSVGCoder, 1.0.0+
+ SDWebImageSVGKitPlugin, 1.0.0+

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    if #available(iOS 13, *) {
        SDImageCodersManager.shared.addCoder(SDImageSVGCoder.shared)
    } else {
        SDImageCodersManager.shared.addCoder(SDImageSVGKitCoder.shared)
    }
    return true
}
```
