### ISSUE TITLE
Redefinition of 'SDImageFormatSVG'

### ISSUE THREAD

**Issue by neobie** [SDWebImage/SDWebImageSVGCoder#20]
SDImageSVGCoder.h
static const SDImageFormat SDImageFormatSVG = 12;

NSData_ImageContentType.h
static const SDImageFormat SDImageFormatSVG       = 8;

**Comment by dreampiggy** [comment]
You must upgrade the SDWebImageSVGCoder to 1.5.0 to be compatible with SDWebImage 5.6.0+. See https://github.com/SDWebImage/SDWebImageSVGCoder/releases/tag/1.5.0
