### ISSUE TITLE
Redefinition of 'SDImageFormatSVG'

### ISSUE THREAD

**Issue by bibin-jaimon** [SDWebImage/SDWebImageSVGCoder#21]
When I install these two libraries using CocoaPod 'SDWebImage' and 'SDWebImageSVGCoder'.

I got error says that 'static const SDImageFormat SDImageFormatSVG = 8' is redefined in

1. NSData+ImageContentType.h in SDWebImage Module 

2. SDImageSVGCoder.h in SDWebImageSVGCoder plugin module

![Screenshot 2020-03-24 at 12 22 55 AM](https://user-images.githubusercontent.com/22428886/77352756-af655680-6d65-11ea-900a-cdbd9bacdddd.png)

![Screenshot 2020-03-24 at 12 22 41 AM](https://user-images.githubusercontent.com/22428886/77352792-c146f980-6d65-11ea-9c63-c336bc5ab49b.png)

How can I resolve this issue?

**Comment by dreampiggy** [comment]
@bibinvazhappillil If you update the SDWebImage to 5.6.0 version, the SVG/PDF coder should also bump to the latest one, because the image type is now built-in.

Update : https://github.com/SDWebImage/SDWebImageSVGCoder/releases/tag/1.5.0

**Comment by eddielisands** [comment]
I am using the latest version from cocoapods and still get the same error.

**Comment by dreampiggy** [comment]
Could you please show me your Podfile.lock after install SDWebImage && SDWebImageSVGCoder ? You can specify the fixed version in your Podfile:

```
pod 'SDWebImage', '5.6.0'
pod 'SDWebImageSVGCoder', '1.5.0'
```

**Comment by dreampiggy** [comment]
Or clean the CocoaPods cache and re-pod install

```
pod cache clean SDWebImage --all
pod cache clean SDWebImageSVGCoder --all
```

**Comment by eddielisands** [comment]
Because my app supports from iOS 12.0, so I couldn't install the latest 'SDWebImageSVGCoder' from cocoapods.
Installing CocoaLumberjack (3.6.1)
Installing SDWebImage (5.6.1)
Installing SDWebImageSVGCoder (0.3.0)
Installing SVGKit (2.1.1)

**Comment by dreampiggy** [comment]
For `SDWebImageSVGCoder` < 1.0 version, it actually use the `SVGKit`.

You should migrate to [SDWebImageSVGKitPlugin](https://github.com/SDWebImage/SDWebImageSVGKitPlugin). The [SVGKitPlugin 1.2.0](https://github.com/SDWebImage/SDWebImageSVGKitPlugin/releases/tag/1.2.0) supports SDWebImage 5.6.0. See more about these two different SVG solution.

https://github.com/SDWebImage/SDWebImageSVGCoder#note-for-svgkit-user

**Comment by dreampiggy** [comment]
And this release note: https://github.com/SDWebImage/SDWebImageSVGCoder/releases/tag/1.0.0

SVGKitPlugin and SVGCoder are totally different codec. For SVGKitPlugin, it supports iOS 8 && macOS 10.10+, which use a **Third party (not Apple written) SVGKit dependency**

For SVGCoder, in before 0.3.0 it's actually what current SVGKitPlugin looks like, but since iOS 13 && macOS 10.15 provide the **Native support (Apple written)**, we use Apple's native support instead in 1.0.0 version.

**Comment by dreampiggy** [comment]
```ruby
pod 'SDWebImage', '5.6.0'
pod 'SDWebImageSVGKitPlugin', '1.2.0'
```

Just change your previous `SDImageSVGCoder` into `SDImageSVGKCoder`, any other things not changed.

**Comment by bibin-jaimon** [comment]
The problem solved when I install   

`pod 'SDWebImage', '~> 5.0'`
`pod 'SDWebImageSVGKitPlugin'`

Thanks,

**Comment by mehmetdelikaya** [comment]
@dreampiggy hi there, I am having issue for displaying a remote svg image via its url in iOS application. I have tried the above versionings but no luck. 
Can you check if you can display the image that i am trying to load? I am also attaching a ss for the expected image

https://storage.opensea.io/files/ecba7c2eb4fbe1f65e8d3f807886a7c8.svg

<img width="1400" alt="Screen Shot 2022-01-06 at 20 40 09" src="https://user-images.githubusercontent.com/16878744/148426481-954b7fd2-1bcf-4ab8-a7c1-5ace0f43f27b.png">
