### ISSUE TITLE
iOS 12 and below support!!

### ISSUE THREAD

**Issue by nikunjgabani** [SDWebImage/SDWebImageSVGCoder#23]
Does this coder supports iOS 12 and below?

**Comment by dreampiggy** [comment]
Currently not. This framework relay on the internal framework introduced in iOS 13+.

If you really need iOS 12 support, try to use third-party open source implementation:

+ https://github.com/SDWebImage/SDWebImageSVGKitPlugin
+ https://github.com/exyte/Macaw

**Comment by dreampiggy** [comment]
Please have a try with the new Adobe-SVG-Native based coder implementation:

https://github.com/SDWebImage/SDWebImageSVGNativeCoder

Feedback are welcomed
