### ISSUE TITLE
Small SVG renders blurry on watchOS

### ISSUE THREAD

**Issue by Maxador** [SDWebImage/SDWebImageSVGCoder#27]
If I try to render an SVG with a bigger size than the SVG file is setting, the image will render blurry.
I tried to use the solution proposed in https://github.com/SDWebImage/SDWebImageSVGCoder/issues/24 but without success.
I had it kinda working by setting values to my `CGSize` like this `[.imageThumbnailPixelSize : CGSize(width: 34, height: 34)]` but unfortunately not all my images are square and I don't want to constraint the width.

**SwiftUI Rendering code**
```swift
WebImage(url: imageURL), context: [.imageThumbnailPixelSize : CGSize.zero])
            .renderingMode(.template)
            .resizable()
            .placeholder(Image(systemName: "photo"))
            .scaledToFit()
            .frame(height: 34)
            .padding(.bottom, 6)
```
|CGSize.zero|CGSize(width: 34, height: 34)|
|-|-|
|![Simulator Screen Shot - Apple Watch Series 6 - 44mm - 2020-12-11 at 09 28 24](https://user-images.githubusercontent.com/1437036/101915151-388e1900-3b93-11eb-98d6-05e7efa2ac72.png)|![Simulator Screen Shot - Apple Watch Series 6 - 44mm - 2020-12-11 at 09 30 20](https://user-images.githubusercontent.com/1437036/101915347-8014a500-3b93-11eb-8657-8439a8a9f071.png)|

Is there a way to render the bitmap to a certain height without requesting a width while keeping the aspect ratio of the image?

**Comment by dreampiggy** [comment]
> Is there a way to render the bitmap to a certain height without requesting a width while keeping the aspect ratio of the image?

Sounds like a new feature request. Can't you pre-calculate the size of length and disable the aspect ratio ?

If you can't, we have to provide some new options, or even like a `calculation size block` closure for advanced use case.
