### ISSUE TITLE
Could not display SVG image

### ISSUE THREAD

**Issue by ASAbdellatif** [SDWebImage/SDWebImageSVGCoder#30]
I want to display SVG image from URL, I am using SDWebImageSVGCoder but it could not display my image, but when I change the image with another one it is displayed correctly.

let svgURL = URL(string: "https://www.sharjahairport.ae/social/svg/ABY.svg")!
    cell.imgView.sd_setImage(with: svgURL) { (image, _, _, _) in
          if let img = image {
              cell.imgView.image = img
           }
     }

**Comment by dreampiggy** [comment]
Seems Apple's CoreSVG rendering engine does not support SVG `pattern` tag.

**Comment by dreampiggy** [comment]
Please have a try with the new Adobe-SVG-Native based coder implementation:

https://github.com/SDWebImage/SDWebImageSVGNativeCoder

Feedback are welcomed
