### ISSUE TITLE
Getting Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT) on loading svg

### ISSUE THREAD

**Issue by ravindran-a** [SDWebImage/SDWebImageSVGCoder#32]
Am using 

SDWebImage
SDWebImageSVGCoder

To Load the following svg

https://gcf-media.s3.ap-south-1.amazonaws.com/subject-tags/practice-cards/Green_color_with_pattern.svg

like this sd_setImage(with: urlString, placeholderImage: placeholderImage)

Getting error as Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

![image](https://user-images.githubusercontent.com/19164536/107792248-ea57ea80-6d7a-11eb-812e-ed08f094498f.png)

I tried using sd_internalSetImage and passing an SDSetImageBlock and tried getting the image and set it by myself but still the same issue occurs.

Any thoughts?

**Comment by dreampiggy** [comment]
Please have a try with the new Adobe-SVG-Native based coder implementation:

https://github.com/SDWebImage/SDWebImageSVGNativeCoder

Feedback are welcomed
