### ISSUE TITLE
can't load this SVG Image

### ISSUE THREAD

**Issue by dev-jiwon** [SDWebImage/SDWebImageSVGCoder#34]
Hi! I love to use SDWebImage Library.

It can't load this Image. please check [this](http://jsfiddle.net/pm1zs0a9/)

thanks!

**Comment by dreampiggy** [comment]
Please have a try with the new Adobe-SVG-Native based coder implementation:

https://github.com/SDWebImage/SDWebImageSVGNativeCoder

Feedback are welcomed
