### ISSUE TITLE
Could not display SVG image correctly in SwiftUI

### ISSUE THREAD

**Issue by koogawa** [SDWebImage/SDWebImageSVGCoder#36]
I want to display SVG image from URL in SwiftUI, I am using SDWebImageSVGCoder but it could not display my image.

```
AnimatedImage(url: URL(string: "https://d4rgq65mqvxhk.cloudfront.net/public/gift_icons/officialGift%2378548ed1-9c95-4634-b355-ca8c2a53da4f.svg"))
```

## Expected result

<img src=https://user-images.githubusercontent.com/893643/145363111-8acf0721-16fd-4f6f-b73d-e36f396426a2.png  width=200>

## Actual result

<img src=https://user-images.githubusercontent.com/893643/145363144-095677b7-6475-49c4-9323-60e7439b9034.png  width=200>

**Comment by dreampiggy** [comment]
Please have a try with the new Adobe-SVG-Native based coder implementation:

https://github.com/SDWebImage/SDWebImageSVGNativeCoder

Feedback are welcomed
