### ISSUE TITLE
Redefinition of 'SDImageFormatSVG'

### ISSUE THREAD

**Issue by nba88719840** [SDWebImage/SDWebImageSVGCoder#45]
<img width="1435" alt="image" src="https://github.com/SDWebImage/SDWebImageSVGCoder/assets/6261850/e13b9714-c828-4c96-ac11-9e322db2a7e4">
 
<img width="706" alt="image" src="https://github.com/SDWebImage/SDWebImageSVGCoder/assets/6261850/dd824df5-eab4-46fc-8763-c834aa16474d">

**Comment by dreampiggy** [comment]
You're using the old deprecated `SDWebImageSVGCoder` version (Which means, SDWebImage Core 5.10+ does not compatible with)

SVGKit based is no-longer maintained. Use 1.0.0+ above

Or choose https://github.com/SDWebImage/SDWebImageSVGNativeCoder

**Comment by dreampiggy** [comment]
https://github.com/SDWebImage/SDWebImageSVGCoder#note-for-svgkit-user

**Comment by nba88719840** [comment]
![Pasted Graphic 1](https://github.com/SDWebImage/SDWebImageSVGCoder/assets/6261850/a3775929-4982-4f71-95b7-a490cc454a49)
thank you for your answer，I looked at this picture, and I thought  SDWebImageSVGKitPlugin was deprecated 😄,After that we can only use SDWebImageSVGNativeCoder？

**Comment by dreampiggy** [comment]
If you really want SVGKit (no longer maintained), that repo is used for those user.

Currently SDWebImage 5.10+ seems  (maybe, not tested) only support:

+ SDWebImageSVGCoder 1.0.0+
+ SDWebImageSVGNativeCoder 0.1.0+
+ SDWebImageSVGKitPlugin 1.0.0+

**Comment by nba88719840** [comment]
<img width="1211" alt="image" src="https://github.com/SDWebImage/SDWebImageSVGCoder/assets/6261850/19c8ed3f-42f7-48ae-9b94-4afb88e00f8e">
demo强制黑暗  setShimmerBackColorInDarkMode 无效
