### ISSUE TITLE
SVG image color after loading

### ISSUE THREAD

**Issue by a-hasan** [SDWebImage/SDWebImageSVGCoder#5]
SVG image color after loading is changed to black

**Comment by dreampiggy** [comment]
What's this `is changed to black` means ?

Did you means `This SVG render correctly on broswer such as Chrome, but looks strange on iOS using SVGCoder` ?

If so, you can provide upload this demo SVG or provide the URL here. But to say, the SVG render part is not the main propose for this repo. You'd better directly report issues to https://github.com/SVGKit/SVGKit.

**Comment by a-hasan** [comment]
Yes, the SVG is rendered correctly on browser but it has black color on image view.
But after some changes on the SVG saving properties using Adobe Illustrator it is looks fine now.
Thanks.

**Comment by embassem** [comment]
> Yes, the SVG is rendered correctly on browser but it has black color on image view.
> But after some changes on the SVG saving properties using Adobe Illustrator it is looks fine now.
> Thanks.
@a-hasan
 what did you change ?

**Comment by a-hasan** [comment]
@embassem ;
According to the designer, in Adobe Illustrator each image should be on her own art board.
do n't use one art board for more than one image.
