### ISSUE TITLE
iWatch error

### ISSUE THREAD

**Issue by fliosan** [SDWebImage/SDWebImageSVGCoder#55]
I am using Xcode 16 and targeting watchOS 11. I added the package using Swift Package Manager from this URL: https://github.com/SDWebImage/SDWebImageSwiftUI. However, Xcode shows the error: "No such module 'SDWebImageSwiftUI'."

How can I fix this issue?

**Comment by dreampiggy** [comment]
Can not reproduce this on my local demo.

I think you need to upload your demo, or simple, remove your project and recreate one with Xcode 16 `New Project`. Something magic blocks you to download SPM package.

[SDWebImageSwiftUIDemo.zip](https://github.com/user-attachments/files/17287103/SDWebImageSwiftUIDemo.zip)

<img width="1334" alt="截屏2024-10-08 11 51 49" src="https://github.com/user-attachments/assets/d176d1d7-ebf3-4bc3-bd3b-15fb10d579e0">

**Comment by fliosan** [comment]
Sorry I found issue with multi scheme.
